name: iOS Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Install CocoaPods
        run: |
          cd ios
          pod install
        working-directory: ios

      - name: Build iOS
        run: |
          xcodebuild -workspace ios/YourProjectName.xcworkspace -scheme YourProjectName -sdk iphoneos -configuration Release -derivedDataPath ios/build
